# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployInfra
  displayName: Deploy Infra Ansible
  jobs:
  - job: DeployInfraAnsible 
    displayName: DeployInfraAnsibleARM
    steps:
      - task: replacetokens@3
        inputs:
          rootDirectory: 'InfraAnsible'
          targetFiles: '**/*.yml'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '__'
          tokenSuffix: '__'
      - task: Ansible@0
        inputs:
          ansibleInterface: 'remoteMachine'
          connectionOverSsh: 'ansiblelab08'
          playbookSourceRemoteMachine: 'agentMachine'
          playbookRootRemoteMachine: 'InfraAnsible'
          playbookPathLinkedArtifactOnRemoteMachine: 'infra.yml'
          inventoriesRemoteMachine: 'hostList'
          inventoryHostListRemoteMachine: 'ansiblelab08.westus.cloudapp.azure.com'

- stage: Role Mysql
  displayName: Role Mysql
  jobs:
  - job: InstallConfigbd
    displayName: InstallConfigbd
    steps:
