# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: DeployInfra
  displayName: Deploy Infra Ansible
  jobs:
  - job: DeployInfraAnsible 
    displayName: DeployInfraAnsibleARM
    steps:
      - task: replacetokens@3
        inputs:
          rootDirectory: 'InfraAnsible'
          targetFiles: '**/*.yml'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '__'
          tokenSuffix: '__'
      - task: Ansible@0
        inputs:
          ansibleInterface: 'remoteMachine'
          connectionOverSsh: 'ansiblelab08'
          playbookSourceRemoteMachine: 'agentMachine'
          playbookRootRemoteMachine: 'InfraAnsible'
          playbookPathLinkedArtifactOnRemoteMachine: 'infra.yml'
          inventoriesRemoteMachine: 'hostList'
          inventoryHostListRemoteMachine: 'ansiblelab08.westus.cloudapp.azure.com'

- stage: RoleMysql
  displayName: Role Mysql
  jobs:
  - job: InstallConfigbd
    displayName: InstallConfigbd
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ansiblelab08'
        sourceFolder: 'Data'
        contents: 'users.sql'
        targetFolder: '/tmp'
    - task: Ansible@0
      inputs:
        ansibleInterface: 'remoteMachine'
        connectionOverSsh: 'ansiblelab08'
        playbookSourceRemoteMachine: 'agentMachine'
        playbookRootRemoteMachine: 'InfraAnsible'
        playbookPathLinkedArtifactOnRemoteMachine: 'mainbd.yml'
        inventoriesRemoteMachine: 'file'
        inventoryFileSourceRemoteMachine: 'agentMachine'
        inventoryFileLinkedArtifactOnRemoteMachine: 'InfraAnsible/inventariobdazure_rm.yml'
        args: '--ssh-extra-args ''-o "StrictHostKeyChecking no"'' --limit=bdlab08_env_bdlab08'
- stage: RoleApache
  displayName: Role Apache
  jobs:
  - job: InstallConfigApache
    displayName: InstallConfigApache
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ansiblelab08'
        sourceFolder: 'Front-End'
        contents: |
          db_connection.php
          delete.php
          index.php
          insert.php
          style.css
          update.php
        targetFolder: '/home/jcubillos555'
    - task: Ansible@0
      inputs:
        ansibleInterface: 'remoteMachine'
        connectionOverSsh: 'ansiblelab08'
        playbookSourceRemoteMachine: 'agentMachine'
        playbookRootRemoteMachine: 'InfraAnsible'
        playbookPathLinkedArtifactOnRemoteMachine: 'mainweb.yml'
        inventoriesRemoteMachine: 'file'
        inventoryFileSourceRemoteMachine: 'agentMachine'
        inventoryFileLinkedArtifactOnRemoteMachine: 'InfraAnsible/inventariowebazure_rm.yml'
        args: '--ssh-extra-args ''-o "StrictHostKeyChecking no"'' --limit=weblab08_env_weblab08'